### ISSUE TITLE
Ingress definition fails when using cert-manager and lets encrypt

### ISSUE THREAD

**Issue by pbuszka** [xetus-oss/helm-charts#1]
TLS cert generation fails when using the chart with cert-manager and lets encrypt. cert-manager fails complaining about missing host in the reuqest :

"ingress-shim controller: Re-queuing item "default/archiva-innect-xetusoss-archiva" due to error processing: secret "repo-tls" for ingress "archiva-innect-xetusoss-archiva" has no hosts specified"  

The fix is to include hosts section in tls definition in the ingress.yaml template

```
  {{- if .Values.ingress.tls.enabled }}
  tls:
   - hosts:
      - {{ .Values.proxy.hostname }}
      secretName: {{ .Values.ingress.tls.secretName }} 
  {{- end }}

```

**Comment by tkent** [comment]
@pbuszka 

Thanks for the report and specific example!  I can see from [the cert-manager docs](https://cert-manager.readthedocs.io/en/latest/reference/ingress-shim.html) that the ```tls.hosts``` key is required.

We'll have this chart updated shortly.

**Comment by tmeneau** [comment]
@pbuszka 

Sorry for the delay in getting to this! Thanks for supplying the fix!

Can you confirm the fix committed to the [fix-archiva-tls-ingress-definition](https://github.com/xetus-oss/helm-charts/tree/fix-archiva-tls-ingress-definition) branch's archiva chart works for you? Once I get confirmation from you we'll go ahead and release that into the xetusoss chart repository.

**Comment by tkent** [comment]
@tmeneau 

Looking over this change, it's safe and low-impact. Let's go ahead and bring it into the master branch and release and updated chart.
