### ISSUE TITLE
Helm failing with "failed to download "xetusoss/xetusoss-archiva"

### ISSUE THREAD

**Issue by cdmaslo** [xetus-oss/helm-charts#14]
When I run a command 
`helm install --debug --namespace=mbp --set persistence.enabled=false archiva xetusoss/xetusoss-archiva`
the relevant error message is:
`install.go:173: [debug] Original chart version: ""
Error: failed to fetch https://xetus-oss.github.com/helm-charts/xetusoss-archiva-0.2.0.tgz : 404 Not Found
helm.go:81: [debug] failed to fetch https://xetus-oss.github.com/helm-charts/xetusoss-archiva-0.2.0.tgz : 404 Not Found`

Maybe it is related "Subdomains of github.com are deprecated for GitHub Pages" - this I see, when I open the https://xetus-oss.github.com/helm-charts/xetusoss-archiva-0.2.0.tgz in browser - see attachment
![image](https://user-images.githubusercontent.com/6020079/122166567-1b0b7600-ce7a-11eb-9f85-bcfa773efc30.png)

Thanks a lot

**Comment by tkent** [comment]
@cdmaslo - Thanks for bringing this to our attention! I'll look into this the first chance I get.
