### ISSUE TITLE
Dependancy points to blank URL

### ISSUE THREAD

**Issue by PaulVanStaden** [xetus-oss/helm-charts#3]
During setup in my cluster I followed https://github.com/xetus-oss/helm-charts/blob/master/README.md

There in it points to <https://xetus-oss.github.io/helm-charts/>

When browsing to <https://xetus-oss.github.io/helm-charts/> I found a 404 page. Please assist

**Comment by tmeneau** [comment]
Thanks for the report, @PaulVanStaden! 

As [described in the Helm docs](https://helm.sh/docs/developing_charts/#the-chart-repository-structure), Helm will actually look for the `index.yaml` file within the chart repository to determine the available charts in a configured helm repository. The 404 page you're seeing is expected, although it wouldn't be expected if you were unable to access the `index.yaml` file.

To make sure this is working for you:

1. Can you confirm you're able to access the `index.yaml` file for the repository: https://xetus-oss.github.io/helm-charts/index.yaml ?
2. Are you seeing the xetus-oss Helm charts via your helm client after you've added the repo as described in the [xetus-oss/helm-charts README](
https://github.com/xetus-oss/helm-charts/blob/master/README.md)?

**Comment by tmeneau** [comment]
I'm going to close this out but feel free to comment here if you still need assistance with this.
